language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
sudo: true
services:
  - docker
install:
  - pip install -U pip
  - pip install -U codacy-coverage
  - pip install -U ".[test,xenon]"
script: py.test -v --flake8 --cov --cov-report xml --cov-report term-missing tests integration_tests simcity
after_script: python-codacy-coverage -r coverage.xml
