language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
install:
    - make install
    - pip install codacy-coverage
script: make fulltest
after_script: python-codacy-coverage -r coverage.xml
