language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
install: 
  - pip install . ".[testing]" codacy-coverage
  - pip install ".[testing]"
script: nosetests --with-coverage --cover-package=simcity --cover-xml
after_script: python-codacy-coverage -r coverage.xml
